version: "3.8"

services:
  web:
    build:
      context: ./src
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - ./src:/app
      - /app/node_modules # Ini adalah target path dalam container (absolut)
    environment:
      - NODE_ENV=development
    command: npm run dev
