name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: cd src && npm install

      - name: Build with Docker
        run: |
          cd src
          docker build -t hut-ri .
          docker create --name hut-ri-container hut-ri
          mkdir -p ../dist
          cp -r public ../dist/
          docker cp hut-ri-container:/app/.next/standalone/. ../dist/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          keep_files: false
